services:
  - type: web
    name: notesapp
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://d2023ankushgemnani:Riyansh%4014@cluster0.jaqfv1r.mongodb.net/notesapp?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: Riyansh@14 