services:
  # Single service for the full stack app
  - type: web
    name: notes-app
    env: node
    buildCommand: |
      npm install
      cd client && npm install --production=false && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
