services:
  # Backend API service
  - type: web
    name: notesapp-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://d2023ankushgemnani:Riyansh%4014@cluster0.jaqfv1r.mongodb.net/notesapp?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: Riyansh@14
      - key: PORT
        value: 5000

  # Frontend service        
  - type: web
    name: notesapp-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_ENV
        value: production
