services:
  # Backend API service
  - type: web
    name: notes-app-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000

  # Frontend service        
  - type: web
    name: notes-app-client
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: notes-app-api
          envVarKey: RENDER_EXTERNAL_URL
